import Head from "next/head";
import Layout from "./Layout";
import Navbar from '../src/components/Navbar'
import HomePage from "./homePage";
import Primera from "./primera";
import Services from "./services";



export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Gionnelly Vielza Durán</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/icono.png" />
      </Head>
      
      <HomePage />
      
      
    </Layout>
  )
}
