import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Gionnelly Vielza Durán</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/icono.png" />
       
      </Head>
      <h1 className="text-3xl font-bold  text-center font-mono  ">
      Ing en Sistemas
    </h1>

     
       
    </div>
  )
}
