import Head from 'next/head'
import Image from 'next/image'
import styles from '../src/styles/Home.module.css'
import Navbar from '../src/components/NavBar'


export default function Home() {
  return (
    <div className='.'>
      <header>
        <title>Gionnelly Vielza Durán</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/icono.png" />
        <Navbar />
      </header>





    </div>
  )
}
